package.json
packages/metabase/.env.example
packages/metabase/Makefile
packages/metabase/docker-compose.yml
packages/metabase/package.json
packages/socket-server/Makefile
packages/socket-server/package.json
turbo.json

- Adiciona .env.example com variáveis de ambiente utilizadas pelo Metabase
- Adiciona docker-compose com configs de deploy do Metabase
https://app.clickup.com/t/86a2atubc

chore(metabase): create docker compose and env example

---

packages/api/src/modules/transaction/services.ts

https://app.clickup.com/t/86a3cvxqv

CHORE: Show workspace transactions on single

---

packages/chain/fuel-core/config/stateConfig.json

https://app.clickup.com/t/86a3bnrmb

chore(chain): set multi asset ids

---

packages/api/package.json
packages/api/src/modules/auth/controller.ts
packages/api/src/modules/user/__tests__/user.tests.ts
packages/api/src/modules/user/controller.ts
packages/api/src/modules/vaultTemplate/controller.ts
packages/api/src/modules/workspace/__tests__/workspace.tests.ts
packages/api/src/modules/workspace/controller.ts
packages/api/src/modules/workspace/services.ts

- update user by other user
- to wk to updates use wk of session

fix: vulnerabilits

---

packages/api/src/modules/user/__tests__/user.tests.ts
packages/api/src/modules/user/controller.ts

- Adds duplicate name validation for WebAuthn users
https://app.clickup.com/t/86a3ucnuv

fix(user): add duplicated name validation in update endpoint

---

packages/api/src/modules/transaction/__tests__/transactions.tests.ts
packages/api/src/modules/transaction/controller.ts

https://app.clickup.com/t/86a3tbcjc

FIX - Transaction: Avoid sign declined transaction

---

packages/api/src/utils/assets.ts

chore(assets): add new BTC and USDC ids

---

packages/api/src/modules/predicate/services.ts

Foi comentado o FAUCET_ADDRESS e as validações

CHORE: Removed logic that remove faucet deposit from deposit list

---

packages/api/src/modules/transaction/__tests__/transactions.tests.ts
packages/api/src/modules/user/__tests__/user.tests.ts

- Adicionado teste do novo endpoint '/user/me/transaction' e na listagem de tx, usando o filtro byMonth

TEST: Home transactions and include transaction by month in list test

---

packages/chain/fuel-core/config/stateConfig.json

- Add new BTC and USDC ids to chain config

chore(assets): add new BTC and USDC ids to chain config

---

packages/api/src/modules/predicate/controller.ts
packages/api/src/modules/predicate/services.ts

https://app.clickup.com/t/86a404trh

FIX: Avoid duplicating deposits

---

packages/api/src/modules/user/__tests__/user.tests.ts
packages/api/src/modules/user/controller.ts
packages/api/src/modules/user/routes.ts
packages/api/src/modules/user/service.ts
packages/api/src/modules/user/types.ts
packages/api/src/server/storage/quote.ts

https://app.clickup.com/t/86a40vkcq

FEAT: Add endpoint to get tokens usd quotes

---

packages/api/src/modules/transaction/utils.ts

https://app.clickup.com/t/86a41zq75

CHORE: Save from address as to address in deposit

---

packages/api/src/modules/workspace/controller.ts

- Fixes build error by renaming the function that calculates the available balance per asset

fix(workspace): renames function that calculates the available balance per asset

---

packages/api/src/modules/user/controller.ts

https://app.clickup.com/t/86a41a5gn

CHORE: Add wk description to meinfo response

---

packages/gateway/src/service/transaction.ts
packages/socket-server/src/modules/transactions.ts
pnpm-lock.yaml

Depends on: https://github.com/infinitybase/bako-safe/pull/50

Implement new transaction summary interface

---

packages/api/src/modules/transaction/controller.ts
packages/api/src/modules/transaction/services.ts
packages/api/src/modules/transaction/types.ts

https://app.clickup.com/t/86a4jv8yc

CHORE: Add filter by id to transaction list with deposits

---

packages/api/src/modules/user/controller.ts
packages/api/src/server/storage/session.ts

- Updates session when updating user data
https://app.clickup.com/t/86a4j2w24

fix(user): updates session when updating user data

---

packages/api/src/modules/transaction/__tests__/transactions.tests.ts
packages/api/src/modules/transaction/controller.ts
packages/api/src/modules/transaction/services.ts
packages/api/src/modules/transaction/types.ts
packages/api/src/modules/transaction/utils.ts
packages/api/src/modules/user/controller.ts

https://app.clickup.com/t/86a4nu2w0

CHORE: Remove group by month logic

---

packages/api/src/modules/predicate/services.ts

https://app.clickup.com/t/86a4p2fwx

FIX: Add workspace permissions to get predicate by id response

---

packages/api/src/modules/predicate/services.ts
packages/api/src/modules/predicate/types.ts
packages/api/src/modules/transaction/utils.ts

We need this operations to adjust deposit cards from spark: https://app.clickup.com/t/86a4r7bbx

CHORE: Add operation fields to deposits

---

packages/api/src/middlewares/auth/methods/strategies/token.ts
packages/api/src/modules/auth/services.ts
packages/api/src/modules/auth/types.ts
packages/api/src/utils/witnessesUpdatedAt.ts

https://app.clickup.com/t/86a4z08uu

FIX: Return user email on auth response and session

---

packages/api/src/middlewares/auth/methods/strategies/token.ts
packages/api/src/modules/auth/services.ts
packages/api/src/modules/auth/types.ts
packages/api/src/modules/user/controller.ts

https://app.clickup.com/t/86a5054ym
this pr is a complement to: https://github.com/infinitybase/bako-safe-ui/pull/409

chore(sigin): added first login to sigin and auth session

---

packages/api/src/modules/auth/controller.ts
packages/api/src/modules/auth/routes.ts

- Removes token from database and session cache when logging out
https://app.clickup.com/t/86a52g5xx

feat(auth): remove token from database and sessions when logging out

---

packages/api/src/modules/predicate/controller.ts

- Removes unnecessary query
https://app.clickup.com/t/86a51tknt

chore(predicate): remove unnecessary query

---

packages/api/src/modules/predicate/controller.ts
packages/api/src/modules/transaction/services.ts
packages/api/src/modules/transaction/utils.ts
packages/api/src/modules/workspace/controller.ts
packages/api/src/server/storage/fuelAssetsFetcher.ts
packages/api/src/server/storage/quote.ts
packages/api/src/utils/assets.ts
packages/api/src/utils/balance.ts
packages/api/src/utils/formatAssets.ts

this pr is a complement for this one: https://github.com/infinitybase/bako-safe-ui/pull/437
https://app.clickup.com/t/86a52y6m0

CHORE: Use verified assets list request instead of assets list from fuels package

---

packages/api/src/modules/addressBook/controller.ts

https://app.clickup.com/t/86a52xd3b

FIX: Error when adding addresses to address book

---

packages/api/src/modules/transaction/controller.ts

https://app.clickup.com/t/86a551c05

FIX: Add network url to transaction findByHash method

---

packages/api/src/modules/transaction/services.ts
packages/api/src/modules/transaction/utils.ts

- Adds network infos to deposits data
https://app.clickup.com/t/86a559xhq

fix(transaction): add network do deposit data

---

packages/api/src/modules/user/controller.ts
packages/api/src/utils/token/utils.ts

fix: order recover code

---

packages/api/src/middlewares/auth/methods/strategies/token.ts
packages/api/src/modules/auth/services.ts
packages/api/src/modules/auth/types.ts
packages/api/src/modules/predicate/controller.ts
packages/api/src/utils/balance.ts

https://app.clickup.com/t/86a54z76a
- this pr is just to solve this topic: 
And also removed some console.logs that i forgot in previous pr

CHORE: Return user nofity field in info request 

---

packages/api/src/modules/transaction/controller.ts

https://app.clickup.com/t/86a52k8rq
complement to this one: https://github.com/infinitybase/bako-safe-ui/pull/476
This PR is to solve this problem:

FIX: When sign transaction update the witness updatedAt field

---

packages/api/src/database/migrations/1728332400808-add-network-to-notifications.ts
packages/api/src/models/Notification.ts
packages/api/src/modules/notification/controller.ts
packages/api/src/modules/notification/services.ts
packages/api/src/modules/notification/types.ts
packages/api/src/modules/predicate/controller.ts
packages/api/src/modules/transaction/controller.ts
packages/api/src/modules/transaction/services.ts
packages/api/src/modules/transaction/types.ts

https://app.clickup.com/t/86a552bux

feat: add network to notifications

---

packages/api/src/modules/transaction/controller.ts
packages/api/src/modules/transaction/utils.ts

https://app.clickup.com/t/86a5930hp
this is to solve the ordernation problem in the tx history

FIX: Improve format tx history method and add a sort to it

---

packages/api/src/modules/predicate/controller.ts

https://app.clickup.com/t/86a58zdtf

fix: filtering nfts

---

packages/api/src/utils/balance.ts

Reverts infinitybase/bako-safe-api#303

Revert "fix(balance): usd balance total value"

---

packages/api/src/utils/token/utils.ts

- Increases token expiration time
https://app.clickup.com/t/86a5bwmcp

chore(token): increate token expiration time to 40 min

---

packages/api/src/models/Predicate.ts
packages/api/src/modules/predicate/controller.ts

this pr is a complement to: https://github.com/infinitybase/bako-safe-ui/pull/539
https://app.clickup.com/t/86a59ejc7

CHORE: Change predicate name column to unique

---

packages/api/src/server/storage/quote.ts
packages/api/src/utils/redis/RedisReadClient.ts
packages/api/src/utils/redis/RedisWriteClient.ts

Fix redis quotes

---

.gitignore
packages/api/src/modules/transaction/controller.ts
packages/api/src/modules/transaction/types.ts
packages/api/src/modules/transaction/utils.ts

Add type in transaction history

feat(transactions): add user type in transactions history

---

packages/api/src/modules/dApps/controller.ts
packages/api/src/socket/client.ts
packages/socket-server/src/index.ts
packages/socket-server/src/socket/index.ts

Adjustments in the client to wait for connection when issuing event, and in the server to wait for dependencies before initializing.

chore(network-socket-exchange-event): adjusted client and API

---

packages/api/src/modules/addressBook/controller.ts

Ajust validation edit address book

Cr/fix/adjusts UI
